modLoader="javafml"
loaderVersion="[40,)"
license="GNU LGPLv3"
issueTrackerURL="https://github.com/auioc/ExtraChampions/issues"

[[mods]]
modId="extrachampions"
version="${file.jarVersion}"
updateJSONURL="https://hi.auioc.org/ExtraChampions/update/1.18.2.json"
displayName="ExtraChampions"
displayURL="https://hi.auioc.org/ExtraChampions/"
logoFile="icon.png"
credits="AUIOC"
authors="WakelssSloth56,Libellule505"
description='''
A Champions Addon adds some new affixes and misc.
'''

[[dependencies.extrachampions]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extrachampions]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extrachampions]]
    modId="arnicalib"
    mandatory=true
    versionRange="[5.3.4,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.extrachampions]]
    modId="champions"
    mandatory=true
    versionRange="[1.18.2-2.1.3.0,)"
    ordering="NONE"
    side="BOTH"
