# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: dev-build

on:
    push:
        branches:
            - 1.18-forge
        tags-ignore:
            - 'v*'
    workflow_dispatch:
        inputs:
            name:
                required: false
                default: 'workflow_dispatch'

jobs:
    first:
        name: Set variables
        runs-on: ubuntu-latest
        outputs:
            ci_version: ${{ steps.set_outputs.outputs.ci_version }}
            full_version: ${{ steps.set_outputs.outputs.full_version }}

        steps:
            - uses: actions/checkout@v2

            - id: set_envs
              name: Set environment variables
              run: |
                  prop() { grep -P "^\s*[^#]?${1}=.*$" './gradle.properties' | cut -d'=' -f2; }
                  echo "EXTRACHAMPIONS_VERSION=`echo $(prop "extrachampions_version")`" >> $GITHUB_ENV
                  echo "MINECRAFT_VERSION=`echo $(prop "minecraft_version")`" >> $GITHUB_ENV
                  echo "CI_VERSION=`echo dev-rev.${GITHUB_SHA:0:7}-build.${{github.run_number}}`" >> $GITHUB_ENV

            - id: set_outputs
              name: Set outputs
              run: |
                  echo "::set-output name=ci_version::${{env.CI_VERSION}}"
                  echo "::set-output name=full_version::extrachampions-${{env.MINECRAFT_VERSION}}-${{env.EXTRACHAMPIONS_VERSION}}-${{env.CI_VERSION}}"

    second:
        name: Build
        runs-on: ubuntu-latest
        needs: first

        steps:
            - uses: actions/checkout@v2

            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  architecture: x64

            - name: Set up Gradle
              run: chmod +x ./gradlew

            - name: Build with Gradle
              env:
                  CI_VERSION: ${{needs.first.outputs.ci_version}}
              run: ./gradlew clean build

            - name: Upload build artifacts
              uses: actions/upload-artifact@v1
              with:
                  name: ${{needs.first.outputs.full_version}}
                  path: build/libs
